gamer_view/urls.py
from django.urls import path
from gamer_view import views

app_name = 'gamer_view'

urlpatterns = [
path('', views.home, name='home'),
path('about/', views.about, name='about'),
path('categories/', views.show_categories, name ='show_categories'),
path('categories/<category_name>/', views.show_category, name='show_category'),
path('categories/<category_name>/<slug:game>/', views.show_page, name='show_page'),
path('add_category/', views.add_category, name='add_category'),
path('add_page/', views.add_page, name='add_page'),
path('add_review/', views.add_review, name='add_review'),
path('trending/', views.trending, name='trending'),
path('register/',views.register, name='register'),
path('login/',views.user_login, name='login'),
path('logout/', views.user_logout, name='logout'),
path('my_account/', views.my_account, name='my_account'),
]

wad_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from gamer_view import views

urlpatterns = [
    path('', views.home, name="home"),
    path('gamer_view/', include('gamer_view.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gamer_view/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Avg
from datetime import datetime

class Category(models.Model):
    
    category=models.CharField(max_length=30, primary_key=True)
    class Meta:
        verbose_name_plural= 'Categories'

    def __str__(self):
        return self.category

class Page(models.Model):
    gamename=models.CharField(max_length=30,unique=True)
    slug = models.SlugField(unique=True, null=True)

    # links the page to category M:1
    cat= models.ForeignKey(Category, on_delete=models.CASCADE)
					   		   
    date_created=models.DateField(default= datetime.now)
    description=models.CharField(max_length=500)
    image = models.ImageField(upload_to='game_images')
    views=models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.gamename)
        super(Page, self).save(*args, **kwargs)
        
    def __str__(self):
        return self.gamename
    
class UserProfile(models.Model):
    
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # The additional attributes we wish to include.
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username
    
class Review(models.Model):
    # Links the review to Page(Game) M:1 
    gamename=models.ForeignKey(Page, on_delete=models.CASCADE, null=True)
      
    review=models.CharField(max_length=500)
    madeby=models.ForeignKey(UserProfile,on_delete=models.CASCADE , null=True)
    datecreated=models.DateField(default=datetime.now)
    rating=models.PositiveSmallIntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])

    def __str__(self):
        return f"{self.gamename}:{self.madeby}"    

gamer_view/forms.py
from django import forms
from gamer_view.models import Page, Category, UserProfile, Review
from django.contrib.auth.models import User

Min=6
Max=30

class UserForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'style': 'height:22.5px; position:relative; top:-6px; font-size:16px; width:205px'
            }
        ), min_length=Min, max_length=Max,required=True,
        error_messages={
            'min_length': 'Choose a username between 6-30 characters',
            'max_length': 'Choose a username between 6-30 characters'
        }                  
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'style': 'height:22.5px; position:relative; top:-6px; font-size:16px; width:287px'
            }
        ),
        error_messages={'invalid': 'Invalid email Address'}
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'style': 'height:22.5px; position:relative; top:-6px; font-size:16px; width:211px'
            }
        ), min_length=Min, max_length=Max,required=True,
        error_messages={
            'min_length': 'Choose a password between 6-30 characters',
            'max_length': 'Choose a password between 6-30 characters'
        }
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    
    picture = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'style': 'height:22.5px; position:relative; top:-6px; font-size:16px; width:210px'
            }
        )
    )
    
    class Meta:
        model = UserProfile
        fields = ('picture',)

class CategoryForm(forms.ModelForm):
    
    category=forms.CharField(max_length=30, required=True)

    class Meta:
        model =Category
        fields=('category',)


class PageForm(forms.ModelForm):
    gamename= forms.CharField(max_length=30, label="Game Name", required=True,
        widget=forms.TextInput(
            attrs={
                'style': 'height:22.5px; position:relative; top:-6px; font-size:16px; width:205px'
            }
        )
    )
    slug= forms.CharField(widget=forms.HiddenInput(), required=False)
    cat=forms.ModelChoiceField(queryset=Category.objects.all(),label="Category", required=True,
        widget=forms.Select(
            attrs={
                'style': 'height:30px; width:150px; position:relative; top:-7px;'
            }
        )
    )
    description=forms.CharField(max_length=500, required=True,
        widget=forms.Textarea(
            attrs={
                'rows': 4,
                'cols': 40,
                'style': 'height:150px; width: 500px; position:relative; top: 70px; font-size: 14px; padding:0.5%; margin-top:-90px'
            }
        )
    )
    image= forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'style': 'height:22.5px; position:relative; top:-6px; font-size:16px; width:210px; padding-top: 70px'
            }
        ),required=True)
    views=forms.IntegerField(widget=forms.HiddenInput(), initial=1)
        
    class Meta:
        model =Page
        fields=('gamename','cat','description', 'image', 'views',)

class ReviewForm(forms.ModelForm):
    gamename=forms.ModelChoiceField(queryset=Page.objects.all(),label="Game Name", required=True,
        widget=forms.Select(
            attrs={
                'style': 'height:30px; position:relative; top:-7px;'
            }
        )
    )
    review=forms.CharField(max_length=500, label="Review",
        widget=forms.Textarea(
            attrs={
                'rows': 4,
                'cols': 40,
                'style': 'height:150px; width: 500px; position:relative; top: 70px; font-size: 14px; padding:0.5%; margin-top:-90px'
            }
        )
    )
    rating=forms.IntegerField(widget=forms.HiddenInput(),initial=1)

    class Meta:
        model= Review
        fields=('gamename','review', 'rating',)

class SearchForm(forms.ModelForm):
    gamename=forms.CharField(max_length=30)

    class Meta:
        model = Page
        fields=('gamename',)

gamer_view/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from gamer_view.forms import UserForm, UserProfileForm ,CategoryForm, PageForm, ReviewForm
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from gamer_view.models import Category, Page, Review ,User, UserProfile
from django.contrib import messages
from django.db.models import Avg, IntegerField
from datetime import datetime

'''
    Home view:
    Displays to the user the 3 latest additions to the site 
'''
def home(request):
    
    # gets the latest added page
    page_list = Page.objects.order_by('-date_created')[:3]

    context_dict={}
    context_dict['pages']=page_list

    if request.method =='POST':
        # formats the input from user to match the slug
        name= (request.POST.get('gamename')).replace(' ' , '-').lower()

        # redirects user to game page if game entered by user exists
        try:
            page=Page.objects.filter(slug=name).values('cat_id')
            return redirect('gamer_view:show_page', page[0]['cat_id'], name)
        except:

            # error message when game does  not exist
             messages.error(request, "Game does not exist")        

    return render(request, 'gamer_view/home.html', context=context_dict)

'''
    About view:
    Displays informations about the site
'''
def about(request):
    return render(request, 'gamer_view/about.html')

'''
    Show Categories view:
    Displays all the categories in the site with thier 3 most viewed games
'''
def show_categories(request):
    context_dict={}
    cat_list={}
    cats = Category.objects.all()
    catE={}
    for cat in cats:
        # gets the games related to the category  
        page=list(Page.objects.filter(cat=cat.category).order_by('-views')[:3])
        if len(page) ==0:
            catE[cat]=page
            continue 
        # creates a dictionary entry with the name of the category as the key and the list of games as the value 
        cat_list[cat]=page

    # puts the categories with empty games at the end of the dictionary so that it would be displayed last
    for cat in catE:
        cat_list[cat]=catE[cat]
        
    context_dict['categories']=cat_list
    return render(request, 'gamer_view/categories.html', context=context_dict)

'''
    Show Category view:
    Displays the category and all its games
'''
def show_category(request, category_name):
    context_dict={}

    try:
        # gets the category name
        category = Category.objects.get(category=category_name)

        
        # get the related games
        pages=Page.objects.filter(cat=category)

        context_dict['pages']=pages
        context_dict['cat']=category

    except Category.DoesNotExist:
        context_dict['cat'] =None
        context_dict['pages']=None

    return render(request, 'gamer_view/category.html', context=context_dict)

'''
    Show Page view:
    Displays the game details and all its reviews 
'''
def show_page(request, category_name, game):
    context_dict={}
    
    try:
        page = Page.objects.get(slug=game)

        # gets the reviews for the game and sorts them in a descending order
        reviews= list(Review.objects.filter(gamename=page).order_by('-datecreated'))

        # gets the average rating for the game using the getAverage function
        rating=getAverage(page)

        context_dict['page']=page
        context_dict['reviews']=reviews
        context_dict['rating']=rating

    except Page.DoesNotExist:
        context_dict['page']=None
        context_dict['reviews']=None
        context_dict['rating']=None

    visitor_handler(request,Page.objects.get(slug=game))
    

    return render(request, 'gamer_view/page.html', context=context_dict)

'''
    Trending view:
    Displays the top 5 most viewed and top rated games in the site
'''
def trending(request):
    context_dict={}
    avg={}
    page_list= Page.objects.all()
    
    for game in page_list:
        
        # creates a dictionary entry with the game as the key and the average rating for the game as the value
        avg[game]=getAverage(game)

    # removes games that do not have reviews
    avg=removeNull(avg)

    # gets the top 5 rated games
    top_rated_pages=sorted(avg, key=avg.get, reverse=True)[:5]
    
    # get the 5 most viewed games
    most_viewed=Page.objects.order_by('-views')[:5]

    context_dict['top_rate_pages']=top_rated_pages
    context_dict['most_viewed']=most_viewed
    return render(request, 'gamer_view/trending.html', context=context_dict)

'''
    Register view:
    Lets users register to our site
'''
def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST,request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True
    
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'gamer_view/register.html', context = {'user_form' : user_form,
                                                                    'profile_form' : profile_form,
                                                                    'registered' : registered})
'''
    User Login view:
    Lets user login if they have an account
'''
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            login(request,user)
            return redirect(reverse('gamer_view:home'))
        else:
            
            # error message when users enter invalid details
            messages.error(request, "Username and/or password is invalid")
            return redirect(reverse('gamer_view:login'))

    else:
        return render(request,'gamer_view/login.html')
    
'''
    User Logout view:
    Lets users logout provided that they are logged in
'''
@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('gamer_view:home'))

'''
    My Account view:
    Displays the user's name, profile picture, reviews made.
    can only be accessed if they are logged in
'''
@login_required
def my_account(request):
    
    user= UserProfile.objects.get(user=request.user)
    Reviews= Review.objects.filter(madeby=user)

    return render(request, 'gamer_view/my_account.html', context={'myReviews':Reviews,
                                                                 'user': user})
'''
    Add Category view:
    Lets users add a category provided that they are logged in
'''
@login_required
def add_category(request):
    form= CategoryForm()

    if request.method =='POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect('gamer_view:show_categories')
        else:
            
            # Error message when the input is empty or the category exists
            messages.error(request, "Your entry must be non-empty and a non-existing category")
            return redirect(reverse('gamer_view:add_category'))
        
    return render(request, 'gamer_view/add_category.html')

'''
    Add Page view:
    Lets users add a game provided that they are logged in
'''
@login_required
def add_page(request):
    if request.method =='POST':
        form = PageForm(request.POST, request.FILES)
        if form.is_valid():
            page= form.save(commit=False)
            try:
                if 'image' in request.FILES:
                    page.image = request.FILES['image']
                    
                page.save()
                
                return redirect('gamer_view:show_page', page.cat, page.slug)
            except:
                page.delete()
                # error message when user tries to add a game with empty field(s)
                messages.error(request, "Game already exising")
                return redirect(reverse('gamer_view:add_page'))
    else:
        form=PageForm()

    return render(request, 'gamer_view/add_page.html', context={'form' :form} )

'''
    Add Review view:
    Lets users add a review provided that they are logged in
'''
@login_required        
def add_review(request):
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review= form.save(commit =False)
            user=UserProfile.objects.get(user=request.user)
            game= (request.POST.get('gamename'))
            revd=Review.objects.filter(madeby=user).values('gamename_id')

            # checks if user already made a review for the game
            for gam in revd:
                if int(gam['gamename_id']) == int(game):
                    messages.error(request, "Cannot make another review for the same game")
                    return redirect('gamer_view:add_review')

            review= form.save(commit =False)
            user=UserProfile.objects.get(user=request.user)   
            review.madeby=user
            review.save()
            return redirect('gamer_view:show_page', review.gamename.cat, review.gamename.slug)

    else:
        form =ReviewForm()
    return render(request, 'gamer_view/add_review.html', context={'form' :form})

'''
    Helper functions:
    getAverage- obtains the all the ratings made in the reviews for a game and calculates its average, returning the integer value

templates/gamer_view/about.html
{% extends 'gamer_view/base.html' %}
{% load static %}

{% block title_block %}
    About Us
{% endblock %}

{% block body_block %}

	<!-- 'About Us' content box and title -->
	<div class="content_box" id="about_content_box">
		<p>About Us</p>
	</div>
	
	<!-- text paragraph of the 'About Us' page -->
	<div id="content_text">
		<p>
			This project was created by 5 Computer Science students using Django for a Web App Development course assignment. We created this site to allow gamers to review and share their opinions on games. 
		</p>
		<p>
			Thank you for using our site!
		</p>
	</div>
	
{% endblock %}

templates/gamer_view/add_category.html
{% extends 'gamer_view/base.html' %}
{% load static %}

{% block title_block %}
	Add Category
{% endblock %}
	
{% block body_block %}

	<!-- 'Add Category' content box -->
    <div class="content_box" id="add_category_content_box">
		<p>Add a Game Category</p>
		{% for mess in messages %}
			<div class="error_message" id="add_category_error"><p>{{ mess }}</p></div>
		{% endfor %}
		<form id="category_form" method="post" action="{% url 'gamer_view:add_category' %}">
			{% csrf_token %}
			<p class="input_details" id="add_category_input">Category Name: <input type="text" name="category" maxlength="30" class="format_input" id="add_category_input_box"/></p>
			<p><input type="submit" value="Add Category" class="page_button" id="add_category_button"/></p>
		</form>
	</div>
	
{% endblock %}

templates/gamer_view/add_page.html
{% extends 'gamer_view/base.html' %}
{% load static %}

{% block title_block %}
	Add Game
{% endblock %}

{% block body_block %}

	<!-- 'Add Page' content box -->
    <div class="content_box">
		<p>Add a Game</p>
		{% for mess in messages %}
			<div class="error_message" id="add_page_error"><p>{{ mess }}</p></div>
		{% endfor %}
		<div class="input_details" id="add_page_details">
			<form id="page_form" method="post" action="{% url 'gamer_view:add_page' %}" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form.as_p }}
			</div>	
			<input type="submit" name="submit" value="Add Game" class="button" id="add_page_button" />
		</form>
	</div>
	
{% endblock %}

templates/gamer_view/add_review.html
{% extends 'gamer_view/base.html' %}
{% load static %}

{% block title_block %}
	Add Review
{% endblock %}

{% block body_block %}

	<!-- 'Add Review' content box -->
	<div class="content_box">
		<p>Make a review</p>
		{% for mess in messages %}
			<div class="error_message" id="add_review_error"><p>{{ mess }}</p></div>
		{% endfor %}
			<form method="POST" action="{% url 'gamer_view:add_review' %}" class="input_details" id="add_review_input">
				{% csrf_token %}
				{{ form.as_p }}
				
				<div class="stars" data-rating="1" id="format_add_review_stars">
					<span class="star">&nbsp;</span>
					<span class="star">&nbsp;</span>
					<span class="star">&nbsp;</span>
					<span class="star">&nbsp;</span>
					<span class="star">&nbsp;</span>
				</div>
				<input type="submit" value="Create Review" class="button" id="add_review_button" />
			</form>
	</div>
	
	<!-- call to star rating javascript -->
	<script src="{% static 'js/star.js' %}"></script>
	
{% endblock %}

templates/gamer_view/base.html
<!DOCTYPE html>
{% load static %}

<html>
	<head>
		<title>
			Gamer-view - 
            {% block title_block %}
                Welcome!
            {% endblock %}
		</title>
		
		<!-- css stylesheets -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/page.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/my_account.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/categories.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/category.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/trending.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/star.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/add_category.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/add_page.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/add_review.css' %}">
	</head>
	
	<body>
	
		<!-- page body reference -->
	    <div>
            {% block body_block %}
            {% endblock %}
        </div>
		
		<!-- formatting of base template -->
		<div id="banner"></div>
		<div id="icon">
			<a href="{% url 'gamer_view:home' %}">
			<img src={% static 'images/controller.png' %} alt="Controller" id="format_icon">
		</div>
		<div id="title">
			<a href="{% url 'gamer_view:home' %}">
				<img src={% static 'images/title.png' %} alt="Title">
			</a>
		</div>

		<!-- profile buttons change dependant on if the user is logged in or logged out -->
		{% if request.user.is_authenticated %}
		<div id="banner_button_1" class="banner_button">
			<p>
				<a href="{% url 'gamer_view:my_account' %}"  id="format_my_account_button">
					My Account
				</a>
			</p>
		</div>
		<div id="banner_button_2" class="banner_button">
			<p>
				<a href="{% url 'gamer_view:logout' %}" id="format_hyperlink">Logout</a>
			</p>
		</div>
		{% else %}
		<div id="banner_button_1" class="banner_button">
			<p>
				<a href="{% url 'gamer_view:login' %}" id="format_hyperlink">Sign In</a>
			</p>
		</div>
		<div id="banner_button_2" class="banner_button">
			<p>
				<a href="{% url 'gamer_view:register' %}" id="format_hyperlink">Register</a>
			</p>
		</div>
		{% endif %}

	</body>
</html>

templates/gamer_view/categories.html
{% extends 'gamer_view/base.html' %}
{% load static %}

{% block title_block %}
	Categories
{% endblock %}

{% block body_block %}

	<!-- area of content to display the categories -->
	<div id="content_area">
	
		<!-- display every category and the latest 3 games from each -->
		{% for cat ,value in categories.items %}
			<div id="category_name" class="button">
				<a href={% url 'gamer_view:show_category' cat.category %} id="format_hyperlink">{{ cat.category }}<br>
				<P id="categories_box"></p>
			</div>
			{% for page in value %}
				<a href={% url 'gamer_view:show_page' cat.category page.slug %}><img src="{{ page.image.url }}" id="format_image" border="2" alt="{{ page.gamename }}"></a>
			{% endfor %}
		{% endfor %}
		<br><br>
	</div>
	
{% endblock %}

templates/gamer_view/home.html
{% extends 'gamer_view/base.html' %}
{% load static %}

{% block title_block %}
    Home
{% endblock %}

{% block body_block %}

	<!-- home page navigation buttons -->
	<div id="category_button" class="button">
	  <a href="{% url 'gamer_view:show_categories' %}" id="format_hyperlink"> Categories </a>
	</div>
	<div id="trending_button" class="button">
	  <a href="{% url 'gamer_view:trending' %}" id="format_hyperlink"> Trending </a>
	</div>
	<div id="about_us_button" class="button">
	  <a href="{% url 'gamer_view:about' %}" id="format_hyperlink">About Us</a>
	</div>
	
	<!-- search bar functionality -->
	<div>
		{% for mess in messages %}
			<div class="error_message" id="search_error"><p>{{ mess }}<p></div>
		{% endfor %} 
		<form id="search_form" method="post" action="{% url 'gamer_view:home' %}">
			{% csrf_token %}
			<div class="button" id="search_bar_button">
				<input placeholder="Search for a game..." type="text" name="gamename" maxlength="30" size="30" id="search_bar_input"/>
			</div>
		</form>
	</div>
	
	<!-- display 3 latest added games -->
	<div id="latest_additions" class="button">
	  <p> Latest Additions </p>
	</div>
	<div id="game_box" class="button">
		<div id="additions_images">
		{% for page in pages %}
			<a href={% url 'gamer_view:show_page' page.cat page.slug %} style="color:black"><img src="{{ page.image.url }}" id="home_image" alt="{{ page.gamename }}"></a>
		{% endfor %}
		</div>
	</div>
	
{% endblock %}

templates/gamer_view/login.html
{% extends 'gamer_view/base.html' %}
{% load static %}

{% block title_block %}
	Login
{% endblock %}

{% block body_block %}
	
	<!-- 'Sign In' content box -->
	<div class="content_box">
	  <p>Sign in to Gamer-View</p>
	  
		<!-- display error message for invalid login input -->
		{% for mess in messages %}
			<div class="error_message"><p>{{ mess }}<p></div>
		{% endfor %} 
		
		<!-- display input form -->
		<form id="login_form" method="POST" action="{% url 'gamer_view:login' %}">
			{% csrf_token %}
			<p class="input_details">Username: <input type="text" name="username" minlength="6" maxlength="30" size="50" class="format_input" /></p>
			<br />
			<p class="input_details">Password: <input type="password" name="password" minlength="6" maxlength="30" size="50" class="format_input" /></p>
			<br />
			<p class="input_details" id="sign_in_button"><input type="submit" value="Sign In" class="button" id="sign_in_button_text" /></p>
		</form>
	</div>
	
{% endblock %}

templates/gamer_view/page.html
{% extends 'gamer_view/base.html' %}
{% load static %}

{% block title_block %}

	<!-- verify game existence -->
    {% if page %}
        {{ page.gamename }}
    {% else %}
        Unknown Game
    {% endif %}
	
{% endblock %}

{% block body_block %}

	<!-- game page content box -->
	<div class="content_box" id="page_box">
		<!-- verify game existence, otherwise display error message -->
		{% if page %}
		
			<!-- game content box -->
			<div class="game_info">
				<p>{{ page.gamename }}</p>
				<div class="page_button">
					<a href= {% url 'gamer_view:show_category' page.cat %} id="format_hyperlink"><p>Category: {{ page.cat }}</p></a>
				</div>
				<div class="page_button" id="description">
					<p>Description: {{ page.description }}</p>
				</div>
			</div>
			<div class="bar"></div>
			<img src="{{ page.image.url }}" id="game_image" border="2" alt="{{ page.gamename }}">
			<div id="average_rating">
				Average Rating: {{ rating }}
			</div>
			
			<!-- review content box -->
			<div class="content_box" id="review_box">
				<p>Reviews:
				
				<!-- add a button to create a review if the user is authorised -->
				{% if request.user.is_authenticated %}
					<div class="banner_button" id="review_add_button">
						<p><a href="{% url 'gamer_view:add_review' %}" id="format_hyperlink">Add Review</a></p>
					</div>
				{% endif %}
				
				<!-- format each review in a box with the creator's name, rating and description -->
				{% if reviews %}
					{% for rev in reviews %}
						<div class="page_button" id="description">
							<p>{{ rev.madeby.user.username }}:
								{% if rev.rating == 1 %}
									<img src={%static "images/1.png" %} id="format_rating" alt="Rating">
								{% endif %}
								{% if rev.rating == 2 %}
									<img src={%static "images/2.png" %} id="format_rating" alt="Rating">
								{% endif %}
								{% if rev.rating == 3 %}
									<img src={%static "images/3.png" %} id="format_rating" alt="Rating">
								{% endif %}
								{% if rev.rating == 4 %}
									<img src={%static "images/4.png" %} id="format_rating" alt="Rating">
								{% endif %}
								{% if rev.rating == 5 %}
									<img src={%static "images/5.png" %} id="format_rating" alt="Rating">
								{% endif %}
							</p>
							{{ rev.review }}
						</div>
					{% endfor %}
					
				<!-- message for if no reviews exist -->
				{% else %}
					<p id="no_review_message">  No reviews available</p>
				{% endif %}
			</div>
		<!-- message for if the game does not exist -->
		{% else %}
			<div id="no_game_error_message">
				The specified game does not exist.
			</div>
		{% endif %}

	</div>

{% endblock %}

templates/gamer_view/register.html
{% extends 'gamer_view/base.html' %}
{% load static %}

{% block title_block %}
Register
{% endblock %}

{% block body_block %}

	<!-- 'Register' page content box -->
	<div class="content_box" id="register_content_box">
	
		<!-- if registered then return a message -->
		{% if registered %}
		<div id="successful_register_content_box">
			<p>Thank you for registering!</p><br/>
			<div class="button" id="register_homepage_return_button">
				<a href="{% url 'gamer_view:home' %}" id="register_homepage_return_button_text">Return to the homepage</a>
			</div>
		</div>
		
		<!-- register form display -->
		{% else %}
		<p>Register to Gamer-View</p>
		<form id="register_page" method="post" action="{% url 'gamer_view:register' %}" enctype="multipart/form-data">
			{% csrf_token %}

			<!-- display each form -->
			{{ user_form.as_p }}
			{{ profile_form.as_p }}

			<!-- provide a button to click to submit the form -->
			<input type="submit" name="submit" value="Register" class="button" id="register_button" />
		</form>
		{% endif %}
	</div>
	
{% endblock %}